sudo /sbin/service hadoop-yarn-nodemanager stop
sudo /sbin/service hadoop-yarn-resourcemanager stop
sudo /sbin/service hadoop-hdfs-namenode stop
sudo /sbin/service hadoop-hdfs-datanode stop
sudo /sbin/service hadoop-mapreduce-historyserver stop
sudo /sbin/service hive-metastore stop
sudo /sbin/service hue stop
sudo /sbin/service mysqld stop
sudo /sbin/service impala-state-store stop
sudo /sbin/service impala-catalog stop
sudo /sbin/service impala-server stop
sudo /sbin/service spark-history-server stop
sudo /sbin/service zookeeper-server stop
