sudo /sbin/service hadoop-yarn-nodemanager start
sudo /sbin/service hadoop-yarn-resourcemanager start
sudo /sbin/service hadoop-hdfs-namenode start
sudo /sbin/service hadoop-hdfs-datanode start
sudo /sbin/service hadoop-mapreduce-historyserver start
sudo /sbin/service hive-metastore start
sudo /sbin/service hue start
sudo /sbin/service mysqld start
sudo /sbin/service impala-state-store start
sudo /sbin/service impala-catalog start
sudo /sbin/service impala-server start
sudo /sbin/service spark-history-server start
sudo /sbin/service zookeeper-server start
